# Generated by Django 4.2 on 2024-06-21 09:35

import account.models
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('father_name', models.CharField(default='', max_length=30, verbose_name='نام پدر')),
                ('pesonal_code', models.CharField(default=account.models.generate_11_digit, help_text='۱۱ رقم', max_length=11, unique=True, verbose_name='کدکارمندی')),
                ('national_code', models.CharField(default=account.models.generate_11_digit, help_text='۱۱ رقم', max_length=11, unique=True, verbose_name='کد ملی')),
                ('telephone', models.CharField(default='', help_text='8 رقم', max_length=8, verbose_name='خط ثابت')),
                ('phone', models.CharField(default='', help_text='۱۱ رقم', max_length=11, verbose_name='شماره تلفن')),
                ('address', models.TextField(default='', verbose_name='آدرس')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربرها',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Register_absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='مثال :\u200c1403', unique=True, verbose_name=' سال به شمسی')),
            ],
            options={
                'verbose_name': 'ثبت مرخصی کارمند در ابتدا سال  ',
                'verbose_name_plural': 'ثبت مرخصی کارمندها در ابتدا سال  ',
            },
        ),
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=30)),
                ('last_name', models.CharField(default='', max_length=150)),
                ('father_name', models.CharField(default='', max_length=30)),
                ('pesonal_code', models.CharField(default=account.models.generate_11_digit, max_length=11, unique=True)),
                ('national_code', models.CharField(default=account.models.generate_11_digit, max_length=30, unique=True, verbose_name='کد ملی')),
                ('telephone', models.CharField(default='', max_length=8)),
                ('phone', models.CharField(default='', max_length=11)),
                ('address', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ استخدام شدن')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publish_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='تاریخ استخدام شدن')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پروفایل کاربر ',
                'verbose_name_plural': 'پروفایل کاربر ها ',
            },
        ),
        migrations.CreateModel(
            name='User_absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('1403', '1403'), ('1404', '1404'), ('1405', '1405'), ('1406', '1406'), ('1407', '1407'), ('1408', '1408'), ('1409', '1409'), ('1410', '1410'), ('1411', '1411'), ('1412', '1412'), ('1413', '1413'), ('1414', '1414'), ('1415', '1415'), ('1416', '1416'), ('1417', '1417'), ('1418', '1418'), ('1419', '1419'), ('1420', '1420')], max_length=4, verbose_name='سال')),
                ('remaining_absence', models.IntegerField(default=30, verbose_name='مرخصی های باقی مانده')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to=settings.AUTH_USER_MODEL, verbose_name='کارمند')),
            ],
            options={
                'verbose_name': 'تعداد مرخصی کارمند',
                'verbose_name_plural': 'تعداد مرخصی کارمندها',
            },
        ),
        migrations.CreateModel(
            name='RegisterAbsenceDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absence_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ مرخصی')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='سال')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absence_date', to=settings.AUTH_USER_MODEL, verbose_name='کارمند')),
            ],
            options={
                'verbose_name': ' ثبت مرخصی',
                'verbose_name_plural': ' ثبت مرخصی ها',
            },
        ),
    ]
