# Generated by Django 4.2 on 2024-06-26 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceRequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absence_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ مرخصی')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='سال')),
                ('status', models.CharField(choices=[('a', 'تایید'), ('d', 'رد')], default='d', max_length=10, verbose_name='وضعیت')),
                ('status_message', models.TextField(blank=True, null=True, verbose_name='پیام مورد نظر برای تایید یا رد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absence_request', to=settings.AUTH_USER_MODEL, verbose_name='کارمند')),
            ],
            options={
                'verbose_name': ' ثبت مرخصی توسط کاربر',
                'verbose_name_plural': ' ثبت مرخصی توسط کاربر ها ',
            },
        ),
    ]
