# Generated by Django 4.2 on 2024-06-26 15:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_absencerequestmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absencerequestmodel',
            name='absence_date',
        ),
        migrations.AddField(
            model_name='absencerequestmodel',
            name='day',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(31), django.core.validators.MinValueValidator(1)], verbose_name='روز'),
        ),
        migrations.AddField(
            model_name='absencerequestmodel',
            name='month',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)], verbose_name='ماه'),
        ),
    ]
