# Generated by Django 4.2 on 2024-06-26 15:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_absencerequestmodel_absence_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absencerequestmodel',
            name='day',
            field=models.IntegerField(blank=True, default=6, null=True, validators=[django.core.validators.MaxValueValidator(31), django.core.validators.MinValueValidator(1)], verbose_name='روز'),
        ),
        migrations.AlterField(
            model_name='absencerequestmodel',
            name='month',
            field=models.IntegerField(blank=True, default=4, null=True, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)], verbose_name='ماه'),
        ),
        migrations.AlterField(
            model_name='absencerequestmodel',
            name='status',
            field=models.CharField(choices=[('a', 'تایید'), ('d', 'رد'), ('w', 'در انتظار')], default='w', max_length=10, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='absencerequestmodel',
            name='year',
            field=models.IntegerField(blank=True, default=1403, null=True, verbose_name='سال'),
        ),
    ]
