# Generated by Django 4.2 on 2024-06-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_absencerequestmodel_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='absencerequestmodel',
            name='absence_length',
            field=models.IntegerField(default=1, verbose_name='طول مرخصی'),
        ),
    ]
